services:
  database:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=database
      - PORT=3000
      - NODE_ENV=${NODE_ENV}
    ports:
      - "3000:3000"
    depends_on:
      - database
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=http://localhost:3000
    ports:
      - "80:80"
    depends_on:
      - server
    restart: unless-stopped

volumes:
  db-data:
    driver: local 